# This workflow will install the dependencies, run tests and lint every push

name: Build Java
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build    
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write 
      id-token: write
    strategy:
      matrix:
        java: [ '8','11' ]
    name: Java ${{ matrix.java }}
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.APP_ID }}
          tenant-id: ${{ secrets.AUTH_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}            
      - uses: actions/checkout@v2
      - name: Setup java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          architecture: x64
          cache: 'maven'
      - name: Run the Maven verify phase
        env:
          LOG4J2_ADX_ENGINE_URL: ${{ secrets.LOG4J2_ADX_ENGINE_URL }}
          LOG4J2_ADX_INGEST_CLUSTER_URL: ${{ secrets.LOG4J2_ADX_INGEST_CLUSTER_URL }}
          LOG4J2_ADX_DB_NAME: ${{ secrets.LOG4J2_ADX_DB_NAME }}
          CI_EXECUTION: 1
        run:
          mvn clean formatter:validate install
      - name: Run the Javadoc generation
        run: mvn javadoc:javadoc
      - name: Run the sources package
        run: mvn source:jar
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        continue-on-error: true
        if: always()
        with:
            files: |
              kusto-log4j-appender/target/surefire-reports/*.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
